server:
  port: 8766

spring:
  application:
    name: user
  data:
    mongodb:
      host: 121.37.137.236
      port: 2024
      database: BeatCode
      username: BeatCode
      password: BeatCode2023summer
      authenticationDatabase: admin
  datasource:
    url: jdbc:mysql://121.37.137.236:2023/beatcode_mysql?serverTimeZone=UTC;
    username: BeatCode
    password: BeatCode2023summer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    serialization:
      fail-on-empty-beans: false
eureka:
  client:
    service-url:
      # where the registry server is
      defaultZone: http://localhost:8761/eureka
