server:
  port: 8765
  address: localhost

spring:
  application:
    name: producer-judge

eureka:
  client:
    service-url:
      # where the registry server is
      defaultZone: http://localhost:8761/eureka

