server:
  port: 8765

spring:
  application:
    # the name of service to be provoked by consumer
    name: judge

eureka:
  client:
    service-url:
      # where the registry server is
      defaultZone: http://localhost:8761/eureka

