server:
  port: 2100
  address: localhost

spring:
  application:
    # the name of service to be provoked by consumer
    name: producer-judge

eureka:
  client:
    service-url:
      # where the registry server is
      defaultZone: http://localhost:8761/eureka

