server:
  port: 8765

spring:
  application:
    # the name of service to be provoked by consumer
    name: judge
  data:
    mongodb:
      host: 121.37.162.88
      port: 1025
      username: BeatCode
      password: BeatCode2023summer
      database: BeatCode

eureka:
  client:
    service-url:
      # where the registry server is
      defaultZone: http://localhost:8761/eureka
judge:
  judgeDirectory: /usr/tmp/BeatCode/judge/1
  dataDirectory: /usr/tmp/BeatCode/data


