server:
  port: 8765

spring:
  application:
    # the name of service to be provoked by consumer
    name: judge
  data:
    mongodb:
      host: 121.37.162.88
      port: 1025
      database: BeatCode
      username: BeatCode
      password: BeatCode2023summer
      authenticationDatabase: admin

eureka:
  client:
    service-url:
      # where the registry server is
      defaultZone: http://localhost:8761/eureka

judge:
  judgeDirectory: /usr/tmp/BeatCode/judge/1
  # dataDirectory: /usr/tmp/BeatCode/data # 未找到调用者，暂且注释掉
  judgerDirectory: /usr/tmp/BeatCode/judger

utils:
  fileVersion:
    jsonPath: /usr/tmp/BeatCode/data/version.json
  extraction:
    executable: 7z
    download: /usr/tmp/BeatCode/Download
    destination: /usr/tmp/BeatCode/data

