server:
  port: 8765

spring:
  application:
    # the name of service to be provoked by consumer
    name: producer-judge
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BeatCode

eureka:
  client:
    service-url:
      # where the registry server is
      defaultZone: http://localhost:8761/eureka


