server:
  port: 8762

spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://121.37.137.236:2023/beatcode_mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: BeatCode
    password: BeatCode2023summer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    ##发送邮件服务器
    host: smtp.qq.com
    # stmp的端口
    smtp:
      port: 587

    # 发送邮件地址，和user一样
    from: 2268253067@qq.com
    # 发送邮件的邮箱地址
    user: 2268253067@qq.com
    # 客户端授权码，并非邮箱密码，为开启服务时腾讯提供
    pass: rgxpjjpuwpxhdjda

eureka:
  client:
    service-url:
      # where the registry server is
      defaultZone: http://localhost:8761/eureka
