server:
  port: 8767

spring:
  application:
    name: submission
  data:
    mongodb:
      host: 121.37.137.236
      port: 2024
      database: BeatCode
      username: BeatCode
      password: BeatCode2023summer
      authenticationDatabase: admin


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
