server:
  port: 8767

spring:
  application:
    name: submission
  data:
    mongodb:
      host: 121.37.162.88
      port: 1025
      database: BeatCode
      username: BeatCode
      password: BeatCode2023summer
  datasource:
    url: jdbc:mysql://121.37.162.88:1023/beatcode_mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: BeatCode
    password: BeatCode2023summer
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
