server:
  port: 8764

spring:
  application:
    name: question-bank
  data:
    mongodb:
      uri: mongodb://localhost:27017/BeatCode
  datasource:
    url: jdbc:mysql://localhost:3306/beatcode_mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: BeatCode
    password: BeatCode2023summer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        dialect: org.hibernate.dialect.MySQLDialect


eureka:
  client:
    service-url:
      # where the registry server is
      defaultZone: http://localhost:8761/eureka

