server:
  port: 8764

spring:
  application:
    name: question-bank
  data:
    mongodb:
#      uri: mongodb://121.37.137.236:2024/BeatCode
#      username: BeatCode
#      password: BeatCode2023summer
        host: 121.37.137.236
        port: 2024
        database: BeatCode
        username: BeatCode
        password: BeatCode2023summer
        authenticationDatabase: admin
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  datasource:
    url: jdbc:mysql://121.37.137.236:2023/beatcode_mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: BeatCode
    password: BeatCode2023summer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      # where the registry server is
      defaultZone: http://localhost:8761/eureka

utils:
  fileVersion:
    storage: /usr/tmp/BeatCode/QBank
  extraction:
    executable: 7z
